/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Posttest3;

import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Desain extends javax.swing.JFrame {

    /**
     * Creates new form Desain
     */
    public Desain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        warna1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        warna2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        warna3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        warna4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cowo = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        prodi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kota = new javax.swing.JComboBox<>();
        tdk = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(80, 80));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));
        jPanel9.setLayout(new java.awt.GridLayout(0, 1, 10, 10));

        jButton1.setText("Tentang");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1);

        jButton2.setText("Foto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel9.add(jButton2);

        jButton3.setText("Visi & Misi");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3);

        jButton4.setText("FORM");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel9.add(jButton4);

        jButton8.setIcon(new javax.swing.ImageIcon("D:\\data nopal\\nopal\\New folder\\3.png")); // NOI18N
        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(543, 100));

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEKOLAH MENENGAH KEJURUAN NEGRI 5 SAMAriNDA");

        jLabel31.setIcon(new javax.swing.ImageIcon("D:\\data nopal\\nopal\\New folder\\nopal.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 50));
        jPanel4.setLayout(new java.awt.CardLayout());

        warna1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel18.setText("Profil SMKN5");

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel19.setText("Sekolah Menengah Kejuruan Negeri 5 (SMKN 5) Samarinda berdiri pada tahun 1982 ");

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel20.setText("merupakan sekolah swasta yang bernama Sekolah Menengah Pekerjaan Sosial (SMPS) ");

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel21.setText("dari swasta menjadi negeri, sesuai dengan Surat Keputusan Menteri Pendidikan dan");

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel22.setText("Kebudayaan Nomor 02.16/0/1992, tanggal 5 Mei 1992 terhitung tanggal 1 April 1992,");

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel23.setText("selanjutnya sesuai dengan UU No. 2 tahun 1989 tentang Sistim Pendidikan Nasional,Maka");

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel24.setText("sejak tahun 1997/1998 sekolah ini berubah lagi namanya menjadi Sekolah Menengah");

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel25.setText("Kejuruan Negeri 5 Samarinda.");

        jLabel26.setIcon(new javax.swing.ImageIcon("D:\\data nopal\\nopal\\New folder\\nopal.png")); // NOI18N

        javax.swing.GroupLayout warna1Layout = new javax.swing.GroupLayout(warna1);
        warna1.setLayout(warna1Layout);
        warna1Layout.setHorizontalGroup(
            warna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warna1Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(30, 30, 30))
            .addGroup(warna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(warna1Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(warna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warna1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(139, 139, 139))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)))
                    .addGap(4, 4, 4)))
        );
        warna1Layout.setVerticalGroup(
            warna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warna1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(244, 244, 244))
            .addGroup(warna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(warna1Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jLabel18)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel20)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel21)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel24)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel25)
                    .addContainerGap(107, Short.MAX_VALUE)))
        );

        jPanel4.add(warna1, "card4");

        warna2.setBackground(new java.awt.Color(51, 204, 0));

        jLabel32.setIcon(new javax.swing.ImageIcon("D:\\wew\\a1.jpg")); // NOI18N

        javax.swing.GroupLayout warna2Layout = new javax.swing.GroupLayout(warna2);
        warna2.setLayout(warna2Layout);
        warna2Layout.setHorizontalGroup(
            warna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warna2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel32)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        warna2Layout.setVerticalGroup(
            warna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warna2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel32)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jPanel4.add(warna2, "card5");

        warna3.setBackground(new java.awt.Color(255, 255, 255));
        warna3.setPreferredSize(new java.awt.Dimension(480, 400));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel9.setText("Visi");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel10.setText("\"Unggul Dalam Menghasilkan Sumber Daya Manusia Tingkat ");

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel11.setText("MenengahYang Mandiri, Kompeten, Beriptek, dan Berimtaq\"");

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel13.setText("a.   Optimalisasi Proses Belajar Mengajar dan Kegiatan  Belajar Mengajar.");

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel12.setText("b.   Mencetak tamatan yang berjiwa Interpreneur. ");

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel14.setText(" c.  Meningkatkan dan mengoptimalkan Potensi dan Sumber Daya Sekolah.");

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel15.setText("d.   Meningkatkan kualitas, kuantitas dan kesejahteraan Guru dan Pegawai.");

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel16.setText("e.   Menghasilkan tamatan yang mampu berkomunikasi dalam Bahasa Inggris, ");

        jLabel17.setIcon(new javax.swing.ImageIcon("D:\\data nopal\\nopal\\New folder\\nopal.png")); // NOI18N

        jLabel27.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel27.setText("Misi");

        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel28.setText("mengoperasikan Komputer dan Internet");

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel29.setText("f.    memfungsikan SMK Negeri 5 Samarinda sebagai Pusat Pendidikan dan ");

        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 10)); // NOI18N
        jLabel30.setText("Pelatihan Kejuruan (PPKT), Community College (CC) dan Crisis Center.");

        javax.swing.GroupLayout warna3Layout = new javax.swing.GroupLayout(warna3);
        warna3.setLayout(warna3Layout);
        warna3Layout.setHorizontalGroup(
            warna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warna3Layout.createSequentialGroup()
                .addGroup(warna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(warna3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9))
                    .addGroup(warna3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(warna3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11))
                    .addGroup(warna3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(warna3Layout.createSequentialGroup()
                .addGroup(warna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(warna3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(warna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addGroup(warna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel30)
                                .addComponent(jLabel29))))
                    .addGroup(warna3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel28)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        warna3Layout.setVerticalGroup(
            warna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warna3Layout.createSequentialGroup()
                .addGroup(warna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(warna3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27))
                    .addGroup(warna3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel4.add(warna3, "card4");

        warna4.setBackground(new java.awt.Color(153, 102, 0));
        warna4.setOpaque(false);
        warna4.setPreferredSize(new java.awt.Dimension(490, 390));

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NISN");

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Kelamin");

        buttonGroup1.add(cowo);
        cowo.setText("Laki-Laki");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Perempuan");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        prodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Multi Media", "Teknik Komputer & Jaringan", "Pemasaran", "Administrasi Bisnis", "Perawatan Sosial", " " }));
        prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jurusan");

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kota/Kab");

        kota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samarinda", "Panajam", "Berau", "Balikpapan", "Tenggarong" }));

        tdk.setText("Tidak");
        tdk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdkActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cetak Tebal");

        jButton5.setText("REGISTER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("RESET");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("PESAN");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FORM PENDAFTARAN");

        javax.swing.GroupLayout warna4Layout = new javax.swing.GroupLayout(warna4);
        warna4.setLayout(warna4Layout);
        warna4Layout.setHorizontalGroup(
            warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warna4Layout.createSequentialGroup()
                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(warna4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(warna4Layout.createSequentialGroup()
                                    .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(46, 46, 46)
                                    .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tdk)
                                        .addGroup(warna4Layout.createSequentialGroup()
                                            .addComponent(cowo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButton2))))
                                .addGroup(warna4Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(jButton5)
                                    .addGap(41, 41, 41)
                                    .addComponent(jButton6)
                                    .addGap(44, 44, 44)
                                    .addComponent(jButton7))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(warna4Layout.createSequentialGroup()
                                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(84, 84, 84)
                                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(warna4Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        warna4Layout.setVerticalGroup(
            warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warna4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cowo)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tdk))
                .addGap(18, 18, 18)
                .addGroup(warna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(warna4, "card3");

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        warna1.setVisible(true);
        warna2.setVisible(false);
        warna3.setVisible(false);
        warna4.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        warna1.setVisible(false);
        warna2.setVisible(true);
        warna3.setVisible(false);
        warna4.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        warna1.setVisible(false);
        warna2.setVisible(false);
        warna3.setVisible(true);
        warna4.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        warna1.setVisible(false);
        warna2.setVisible(false);
        warna3.setVisible(false);
        warna4.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void prodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiActionPerformed

    private void tdkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdkActionPerformed
        // TODO add your handling code here:
        if(tdk.isSelected()){
            tdk.setText("Ya");
        }
        else{
            tdk.setText("Tidak");
        }
    }//GEN-LAST:event_tdkActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Font font;
        String kotaa = kota.getSelectedItem().toString();
        String prodii = prodi.getSelectedItem().toString();
        if(tdk.isSelected()){
            //font tebal
            font = new Font ("Monospaced", Font.BOLD,12);
        }else{
            ///font biasa
            font = new Font ("Monospaced", Font.PLAIN,12);
        }

        String JenisKelamin = null;
        if(cowo.isSelected())
        JenisKelamin = cowo.getText();
        else if(jRadioButton2.isSelected())
        JenisKelamin = jRadioButton2.getText();

        String name = nama.getText();
        String nimm = nim.getText();

        jTextArea1.setText("Nama\t: " +name+ "\nNim\t: " +nimm+ "\nJenisKelamin\t: "+JenisKelamin+ "\nProdi\t\t: " +prodii+ "\nKota/Kab\t: "+kotaa);
        jTextArea1.setFont(font);
        }

        private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {
            // TODO add your handling code here:
            if(tdk.isSelected())
            {
                tdk.setText("YA");
            }
            else
            {
                tdk.setText("TIDAK");
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        nama.setText("");
        nim.setText("");
        jTextArea1.setText("");
        buttonGroup1.clearSelection();        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(null,"Naufal Saputra \n 1515015210","DATA DIRI",JOptionPane.PLAIN_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Naufal Saputra \n 1515015210","DATA DIRI",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cowo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> kota;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JComboBox<String> prodi;
    private javax.swing.JCheckBox tdk;
    private javax.swing.JPanel warna1;
    private javax.swing.JPanel warna2;
    private javax.swing.JPanel warna3;
    private javax.swing.JPanel warna4;
    // End of variables declaration//GEN-END:variables
}
